### ISSUE TITLE
give hints for missing libraries on Linux distributions

### ISSUE THREAD

**Issue by stragu** [krahim/fftwtools#17]
I was trying to install a package that depends on fftwtools today, with the following error:

```
* installing *source* package ‘fftwtools’ ...
** package ‘fftwtools’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for pkg-config... yes
Package fftw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `fftw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fftw3' found
Package fftw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `fftw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fftw3' found
configure: creating ./config.status
config.status: creating src/Makevars

fftwtools 0.9-10
================

compiler flags:  
link argument:   

** libs
gcc -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-apO4Ea/r-base-4.2.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fftwtools.c -o fftwtools.o
fftwtools.c:28:9: fatal error: fftw3.h: No such file or directory
   28 | #include<fftw3.h>
      |         ^~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:168: fftwtools.o] Error 1
ERROR: compilation failed for package ‘fftwtools’
```

After a bit of searching, I figured out I was missing the `libfftw3-dev` package on my Ubuntu 20.04. Installing it allowed me to install fftwtools.

Would it be possible to hind at the right packages that need installing, like when other packages fail installing? I am not sure how that is set up, but I remember seeing such hints before. (e.g. "on Debian/Ubuntu, use `apt install libfftw3-dev`", etc.)

**Comment by krahim** [comment]
Hi,

Take a look at:
https://cran.r-project.org/package=fftwtools

Specifically: 


NeedsCompilation: | yes
SystemRequirements: | fftw3 (libfftw3-dev (deb), or fftw-devel (rpm))

What else would you like me to add?

**Comment by stragu** [comment]
Thanks for the reply! It took me a while to find an example, but here is how magick does it:

https://github.com/ropensci/magick/blob/7d8b819790d5a6ef20d7984248c0c70902429a6e/configure#L70-L90

This could make it a lot easier for people to fix their dependency problem, especially if the error pops up because fftwtools is a dependency of another package that's being installed (as the user would have been very unlikely to review fftwtools' CRAN page).

**Comment by krahim** [comment]
Thanks,

I feel the dependencies are clear--explicit package names for Deb and Redhat are specified on the R page--but it could always be more clear.  

You are asking me to modify the configure script to give more precise warning messages?
It's someting I could do. I don't consider it urgent. I will wait to see if there is more feedback before changing this.

Karim

**Comment by stragu** [comment]
No problem, thank you for the reply, Karim!
