### ISSUE TITLE
PKG_CHECK_MODULES not defined in configure.ac

### ISSUE THREAD

**Issue by dipterix** [krahim/fftwtools#7]
Hi, 
I encountered building problem when installing your package using non-standard prefix for fftw headers: it cannot find `fftw3.h` even when I manually set `FFTW_CFLAGS` and `FFTW_LIBS` in my `.Renviron` file:
```
FFTW_CFLAGS="-I/data/shared/miniconda3/include"
FFTW_LIBS="-L/data/shared/miniconda3/lib -lfftw3"
```

I can compile and install FFTW package but not fftwtools.

**Comment by dipterix** [comment]
I forked your repository and did some changes. At least it works on mine. Here's notes to those who have the same problem:

1. removed `configure` in `.Rbuildignore` and `.gitignore`
2. renamed `src/Makevars` to `src/Makevars.in`
3. edited `src/Makevars.in` to the following to respect user-defined `FFTW_CFLAGS` and `FFTW_LIBS`
```
PKG_CPPFLAGS=@CPPFLAGS@ @FFTW_CFLAGS@
PKG_LIBS=@LIBS@ @FFTW_LIBS@
all: $(SHLIB)
```
4. inserted line 38 to 168 in [fftw configure.ac](https://github.com/cran/fftw/blob/master/configure.ac) to fftwtools `configure.ac`, right after `AC_INIT()`.
5. git ignores `src/Makevar`
6. run `autoconf` to generate `configure` file

**Comment by krahim** [comment]
This has come up on the R_devel email group.
Basically  you need to install FFTW in a way that the header file, fftw3.h is visible.

Try the following packages depending on the Linux OS.  I've added this to the dependencies listed in DESCRIPTION
libfftw3-dev (deb)
fftw-devel (rpm)

**Comment by krahim** [comment]
Thanks @dipterix.

I look into this and likely make the updates.

Thanks,
Kairm

**Comment by krahim** [comment]
Actually @dipterix 

Is it possible to ask you to make a pull request ?

Thanks,
Karim

**Comment by krahim** [comment]
Sorry @dipterix
I wasn't able to compile it without warnings and notes --as-cran. 
I wasn't able to spend the time time to debug it. I submitted an upload to CRAN with the 3d transform.
You are welcome if you want to try again.
I will likely do an update in six months
